### ISSUE TITLE
Stop using legacy lifecycle method "componentWillUpdate"

### ISSUE THREAD

**Issue by jackwilsdon** [hjnilsson/react-html-id#3]
It looks like this library uses the lifecycle method "componentWillUpdate" which is deprecated in React 16.3 and will be removed in the future.

I'm not sure what we can use as an alternative, maybe switching to the UNSAFE variant for now?

**Comment by hampusborgos** [comment]
Appropriate way to do this is probably to just wrap `render` instead. Will make the change and publish a new version.

**Comment by saxoncameron** [comment]
@hjnilsson - did you ever publish that new version? Latest version is 0.1.4 and is prior to your commit 46ea85e2841af299517ca7ab0a2072207750b252

**Comment by hampusborgos** [comment]
Hello, I have published v 0.1.5 now. Been on vacation past month so missed to publish. :)

Thanks for reminding me!

**Comment by ghost** [comment]
So does this mean that this ~error~ issue is fixed? Can it be closed if that's the case?

(Thank you for your hard work!)

**Comment by jackwilsdon** [comment]
Looks like it was fixed in 46ea85e2841af299517ca7ab0a2072207750b252, I'll go ahead and close this. Cheers!
